// <auto-generated />
namespace Ubg_Api_v4.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class SecondTry : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(SecondTry));
        
        string IMigrationMetadata.Id
        {
            get { return "201806130958169_SecondTry"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
