// <auto-generated />
namespace Ubg_Api_v4.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class RefId_in_Notifications : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(RefId_in_Notifications));
        
        string IMigrationMetadata.Id
        {
            get { return "201807021256143_RefId_in_Notifications"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
